device id 0
>>>>>>>testing : ALL_task_UniTS_zeroshot_pretrain_x64_mine_all_new_4_1_test_UniTS_zeroshot_All_ftM_dm64_el3_'Exp'_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "C:\Users\lzuzi\Documents\GitHub\MarkovOtoTrak3\run.py", line 182, in <module>
    exp.test(setting, load_pretrain=True)
  File "C:\Users\lzuzi\Documents\GitHub\MarkovOtoTrak3\exp\exp_sup.py", line 536, in test
    test_data_list, test_loader_list = self._get_data(
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\lzuzi\Documents\GitHub\MarkovOtoTrak3\exp\exp_sup.py", line 204, in _get_data
    data_set, data_loader = data_provider(
                            ^^^^^^^^^^^^^^
  File "C:\Users\lzuzi\Documents\GitHub\MarkovOtoTrak3\data_provider\data_factory.py", line 119, in data_provider
    data_set = Data(
               ^^^^^
  File "C:\Users\lzuzi\Documents\GitHub\MarkovOtoTrak3\data_provider\data_loader.py", line 233, in __init__
    self.__read_data__()
  File "C:\Users\lzuzi\Documents\GitHub\MarkovOtoTrak3\data_provider\data_loader.py", line 264, in __read_data__
    self.scaler.fit(train_data.values)
  File "C:\Users\lzuzi\anaconda3\Lib\site-packages\sklearn\preprocessing\_data.py", line 824, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lzuzi\anaconda3\Lib\site-packages\sklearn\preprocessing\_data.py", line 861, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lzuzi\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lzuzi\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 931, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by StandardScaler.